### ISSUE TITLE
Add network usage

### ISSUE THREAD

**Issue by Tiebe** [djtimca/googlewifi-api#6]
Is it possible to retrieve network usage through the api? (ie see amount of MBs used today)

**Comment by djtimca** [comment]
Not that I've found. I have exposed everything I get in the payload in the integration.

**Comment by Tiebe** [comment]
Ahh that's too bad. Do you have a guess to how Google achieves this in their apps?

**Comment by djtimca** [comment]
Unfortunately no idea. Not sure it uses this API for that purpose.
